name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3

# name: Docs

# on: 
#   push:
#     branches: [master]

# permissions:
#     contents: write
    
# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v3
#       - name: Install dependencies
#         run: |
#           pip install sphinx sphinx_rtd_theme recommonmark
#       - name: Sphinx build
#         run: |
#           sphinx-build docs _build
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#         with:
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: _build/
#           force_orphan: true